<?php
require_once __DIR__ . '/../db.php';
require_once __DIR__ . '/../helpers.php';
require_once __DIR__ . '/../services/metaWhatsAppService.php';
require_once __DIR__ . '/../services/whatsappAutomationService.php';
require_once __DIR__ . '/../services/tenantFeatureService.php';
require_once __DIR__ . '/../services/aiService.php';

class WhatsAppController {
    private function db() { return DB::getConnection(); }
    private function assertClientInClinic($db,$clientId,$clinicId){$stmt=$db->prepare("SELECT id FROM Client WHERE id=? AND clinicId=?");$stmt->execute([$clientId,$clinicId]);if(!$stmt->fetch())send_error('Patient not found',404);}
    private function settings($db, $clinicId) { $stmt=$db->prepare("SELECT * FROM WhatsAppSetting WHERE clinicId=?"); $stmt->execute([$clinicId]); return $stmt->fetch() ?: ['clinicId'=>$clinicId,'simulationMode'=>1,'apiVersion'=>'v23.0']; }
    private function features($db, $clinicId) { return tenant_features_get($db, $clinicId); }
    private function requireFeature($db, $clinicId, $feature, $message) { if (!tenant_feature_bool($this->features($db, $clinicId), $feature)) send_error($message, 403); }
    private function publicSettings($settings) { $settings['hasAccessToken']=!empty($settings['accessToken']); unset($settings['accessToken']); return $settings; }
    private function templatePayload($template,$language='en',$components=[]){$payload=['name'=>$template,'language'=>['code'=>$language]];if($components)$payload['components']=$components;return ['type'=>'template','template'=>$payload];}
    private function segmentWhere($segment){$date=DB_DRIVER==='sqlite'?"date('now','-%d day')":"DATE_SUB(CURDATE(), INTERVAL %d DAY)";$today=DB_DRIVER==='sqlite'?"substr(date('now'),6,5)":"DATE_FORMAT(CURDATE(),'%m-%d')";$segments=['all'=>"1=1",'new'=>"createdAt >= ".sprintf($date,30),'returning'=>"totalSpent > 0",'vip'=>"loyaltyTier IN ('Gold','Platinum') OR totalSpent >= 100000",'birthday'=>"substr(dob,6,5)=$today",'high_spending'=>"totalSpent >= 100000",'inactive_30'=>"lastVisit IS NOT NULL AND lastVisit < ".sprintf($date,30),'inactive_60'=>"lastVisit IS NOT NULL AND lastVisit < ".sprintf($date,60),'inactive_90'=>"lastVisit IS NOT NULL AND lastVisit < ".sprintf($date,90),'inactive_180'=>"lastVisit IS NOT NULL AND lastVisit < ".sprintf($date,180),'dental'=>"specialty LIKE '%dental%'",'aesthetics'=>"specialty LIKE '%aesthetic%'",'implant'=>"notes LIKE '%implant%' OR specialty LIKE '%implant%'",'orthodontic'=>"notes LIKE '%ortho%' OR specialty LIKE '%ortho%'",'skin'=>"notes LIKE '%skin%' OR specialty LIKE '%skin%'",'laser'=>"notes LIKE '%laser%' OR specialty LIKE '%laser%'",'membership'=>"loyaltyTier IN ('Gold','Platinum')",'branch_based'=>"EXISTS (SELECT 1 FROM Appointment a WHERE a.clientId=Client.id AND a.branchId IS NOT NULL)",'treatment_based'=>"EXISTS (SELECT 1 FROM Appointment a WHERE a.clientId=Client.id AND a.serviceId IS NOT NULL)"];return $segments[$segment]??$segments['all'];}
    private function conversation($db, $clinicId, $clientId) { $stmt=$db->prepare("SELECT * FROM WhatsAppConversation WHERE clinicId=? AND clientId=?"); $stmt->execute([$clinicId,$clientId]); $row=$stmt->fetch(); if($row) return $row; $id=generate_uuid(); $db->prepare("INSERT INTO WhatsAppConversation(id,clinicId,clientId) VALUES(?,?,?)")->execute([$id,$clinicId,$clientId]); return ['id'=>$id,'clinicId'=>$clinicId,'clientId'=>$clientId,'status'=>'open']; }
    private function queue($db,$clinicId,$clientId,$conversationId,$phone,$payload,$purpose,$error){$id=generate_uuid();$db->prepare("INSERT INTO WhatsAppQueue(id,clinicId,clientId,conversationId,phone,payloadJson,purpose,status,attempts,lastError,nextRetryAt) VALUES(?,?,?,?,?,?,?,'pending',1,?,?)")->execute([$id,$clinicId,$clientId,$conversationId,$phone,json_encode($payload),$purpose,$error,date('Y-m-d H:i:s',strtotime('+10 minutes'))]);return $id;}
    private function interpolate($body,$client,$clinic){ return str_replace(['{{name}}','{{clinic}}','{{balance}}'],[$client['name'],$clinic['name'],number_format(floatval($client['outstandingBalance']))],$body); }
    public function dashboard($input,$user){ $db=$this->db(); $c=$user['clinicId']; $features=$this->features($db,$c); if(empty($features['whatsappEnabled']))send_error('Contact Support to activate WhatsApp Center.',403,['code'=>'feature_inactive']); $summary=$db->prepare("SELECT COALESCE(SUM(CASE WHEN direction='outbound' THEN 1 ELSE 0 END),0) AS sent, COALESCE(SUM(CASE WHEN direction='outbound' AND deliveryStatus IN ('delivered','read') THEN 1 ELSE 0 END),0) AS delivered, COALESCE(SUM(CASE WHEN direction='outbound' AND deliveryStatus='read' THEN 1 ELSE 0 END),0) AS readCount, COALESCE(SUM(CASE WHEN direction='inbound' THEN 1 ELSE 0 END),0) AS responses, COALESCE(SUM(cost),0) AS cost FROM WhatsAppMessage WHERE clinicId=?"); $summary->execute([$c]); $m=$summary->fetch(); $campaign=$db->prepare("SELECT COALESCE(SUM(conversionCount),0) AS conversions,COALESCE(SUM(revenue),0) AS revenue FROM WhatsAppCampaign WHERE clinicId=?");$campaign->execute([$c]);$cp=$campaign->fetch(); $m=array_merge($m,$cp); $sent=max(1,intval($m['sent'])); send_json(['metrics'=>['sent'=>intval($m['sent']),'deliveryRate'=>round(100*intval($m['delivered'])/$sent),'readRate'=>round(100*intval($m['readCount'])/$sent),'responseRate'=>round(100*intval($m['responses'])/$sent),'conversions'=>intval($m['conversions']),'revenue'=>floatval($m['revenue']),'cost'=>floatval($m['cost'])],'features'=>['whatsappEnabled'=>!empty($features['whatsappEnabled']),'whatsappMarketingEnabled'=>!empty($features['whatsappMarketingEnabled']),'whatsappAutomationEnabled'=>!empty($features['whatsappAutomationEnabled']),'monthlyWhatsAppLimit'=>intval($features['monthlyWhatsAppLimit']??0),'aiAutoReplyEnabled'=>!empty($features['aiAutoReplyEnabled']),'aiHumanApprovalRequired'=>!empty($features['aiHumanApprovalRequired'])],'settings'=>$this->publicSettings($this->settings($db,$c))]); }
    public function contacts($input,$user){ $db=$this->db();$q=$_GET['search']??'';$stmt=$db->prepare("SELECT c.*, (SELECT COUNT(*) FROM Appointment a WHERE a.clientId=c.id AND a.clinicId=c.clinicId) appointmentCount,(SELECT MAX(date) FROM Appointment a WHERE a.clientId=c.id AND a.clinicId=c.clinicId) lastAppointment,(SELECT body FROM WhatsAppMessage m WHERE m.clientId=c.id AND m.clinicId=c.clinicId ORDER BY createdAt DESC LIMIT 1) lastMessage FROM Client c WHERE c.clinicId=? AND c.status='active' AND (c.name LIKE ? OR c.phone LIKE ?) ORDER BY c.name");$like="%$q%";$stmt->execute([$user['clinicId'],$like,$like]);send_json($stmt->fetchAll()); }
    public function profile($input,$user,$id){ $db=$this->db();$stmt=$db->prepare("SELECT * FROM Client WHERE id=? AND clinicId=?");$stmt->execute([$id,$user['clinicId']]);$client=$stmt->fetch();if(!$client)send_error('Patient not found',404);$stmt=$db->prepare("SELECT a.*,s.name staffName,srv.name serviceName FROM Appointment a LEFT JOIN Staff s ON s.id=a.staffId AND s.clinicId=a.clinicId LEFT JOIN Service srv ON srv.id=a.serviceId AND srv.clinicId=a.clinicId WHERE a.clientId=? AND a.clinicId=? ORDER BY date DESC");$stmt->execute([$id,$user['clinicId']]);send_json(['client'=>$client,'appointments'=>$stmt->fetchAll()]); }
    public function messages($input,$user,$clientId){ $db=$this->db();$this->assertClientInClinic($db,$clientId,$user['clinicId']);$conversation=$this->conversation($db,$user['clinicId'],$clientId);$stmt=$db->prepare("SELECT * FROM WhatsAppMessage WHERE conversationId=? AND clinicId=? ORDER BY createdAt ASC");$stmt->execute([$conversation['id'],$user['clinicId']]);send_json(['conversation'=>$conversation,'messages'=>$stmt->fetchAll()]); }

    // AI draft reply for a conversation (human reviews + sends — never auto-sent).
    // Uses the super-admin's shared platform AI key.
    public function aiSuggest($input,$user,$clientId){
        $db=$this->db();
        $this->requireFeature($db,$user['clinicId'],'whatsappEnabled','WhatsApp is not enabled for this clinic plan.');
        if(!ai_is_configured($db)) send_error('AI is not configured yet. Ask the platform admin to add an AI key under Platform settings.',400);
        $this->assertClientInClinic($db,$clientId,$user['clinicId']);

        $cs=$db->prepare("SELECT name FROM Client WHERE id=? AND clinicId=?"); $cs->execute([$clientId,$user['clinicId']]); $client=$cs->fetch();
        $cl=$db->prepare("SELECT name,clinicType FROM Clinic WHERE id=?"); $cl->execute([$user['clinicId']]); $clinic=$cl->fetch();

        $conversation=$this->conversation($db,$user['clinicId'],$clientId);
        $hist=$db->prepare("SELECT direction,body FROM WhatsAppMessage WHERE conversationId=? AND clinicId=? AND body IS NOT NULL AND body<>'' ORDER BY createdAt DESC LIMIT 12");
        $hist->execute([$conversation['id'],$user['clinicId']]);
        $rows=array_reverse($hist->fetchAll());
        if(!$rows) send_error('No patient messages yet to reply to.',400);

        $clinicName=$clinic['name']??'the clinic';
        $type=$clinic['clinicType']??'dental';
        $system="You are the front-desk assistant for {$clinicName}, a {$type} clinic. Draft a short, warm, professional WhatsApp reply to the patient"
               .($client?(' ('.$client['name'].')'):'')
               .". Rules: under 55 words; no medical diagnosis or treatment advice — for clinical questions, invite them to book or visit; match the patient's language (e.g. Urdu/English); be specific and helpful; no placeholders like [name].";
        $messages=[['role'=>'system','content'=>$system]];
        foreach($rows as $r){ $messages[]=['role'=>($r['direction']==='inbound'?'user':'assistant'),'content'=>$r['body']]; }

        try{
            $suggestion=ai_complete($db,$messages,['maxTokens'=>180,'temperature'=>0.5]);
            send_json(['suggestion'=>$suggestion]);
        }catch(Exception $e){
            send_error($e->getMessage(),502);
        }
    }
    public function send($input,$user,$clientId){ $db=$this->db();$this->requireFeature($db,$user['clinicId'],'whatsappEnabled','WhatsApp is not enabled for this clinic plan.');$stmt=$db->prepare("SELECT * FROM Client WHERE id=? AND clinicId=?");$stmt->execute([$clientId,$user['clinicId']]);$client=$stmt->fetch();if(!$client||!$client['phone'])send_error('Patient phone number is required',400);$purpose=$input['purpose']??'support';if($purpose==='marketing'){$this->requireFeature($db,$user['clinicId'],'whatsappMarketingEnabled','WhatsApp marketing is not enabled for this clinic.');if(!intval($client['whatsappMarketingOptIn']??0))send_error('Marketing consent is not recorded for this patient.',400);}$conversation=$this->conversation($db,$user['clinicId'],$clientId);$settings=$this->settings($db,$user['clinicId']);if(empty($settings['simulationMode'])&&(empty($conversation['freeReplyUntil'])||strtotime($conversation['freeReplyUntil'])<time()))send_error('Free reply window is closed. Please send an approved Meta template.',400);$type=$input['messageType']??'text';$body=$input['body']??'';$payload=$type==='text'?['type'=>'text','text'=>['preview_url'=>false,'body'=>$body]]:['type'=>$type,$type=>['link'=>$input['mediaUrl']??'','caption'=>$body]];try{$sent=meta_whatsapp_send($settings,$client['phone'],$payload);}catch(Exception $e){$queueId=$this->queue($db,$user['clinicId'],$clientId,$conversation['id'],$client['phone'],$payload,$purpose,$e->getMessage());send_error($e->getMessage().' Saved to retry queue.',502,['queueId'=>$queueId]);}$id=generate_uuid();$db->prepare("INSERT INTO WhatsAppMessage(id,clinicId,conversationId,clientId,direction,purpose,messageType,body,mediaUrl,metaMessageId,deliveryStatus,sentBy) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)")->execute([$id,$user['clinicId'],$conversation['id'],$clientId,'outbound',$purpose,$type,$body,$input['mediaUrl']??null,$sent['messageId'],$sent['status'],$user['id']??null]);send_json(['id'=>$id,'status'=>$sent['status'],'simulation'=>$sent['simulation']],201); }
    public function sendTemplate($input,$user,$clientId){ $db=$this->db();$this->requireFeature($db,$user['clinicId'],'whatsappEnabled','WhatsApp is not enabled for this clinic plan.');$stmt=$db->prepare("SELECT * FROM Client WHERE id=? AND clinicId=?");$stmt->execute([$clientId,$user['clinicId']]);$client=$stmt->fetch();if(!$client||!$client['phone'])send_error('Patient phone number is required',400);$name=$input['templateName']??'';if(!$name)send_error('Template is required',400);$conversation=$this->conversation($db,$user['clinicId'],$clientId);$sent=meta_whatsapp_send($this->settings($db,$user['clinicId']),$client['phone'],$this->templatePayload($name,$input['language']??'en'));$id=generate_uuid();$db->prepare("INSERT INTO WhatsAppMessage(id,clinicId,conversationId,clientId,direction,purpose,messageType,body,templateName,metaMessageId,deliveryStatus,sentBy) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)")->execute([$id,$user['clinicId'],$conversation['id'],$clientId,'outbound',$input['purpose']??'appointment','template',$input['body']??$name,$name,$sent['messageId'],$sent['status'],$user['id']??null]);send_json(['id'=>$id,'status'=>$sent['status'],'simulation'=>$sent['simulation']],201); }
    public function templates($input,$user){$db=$this->db();$stmt=$db->prepare("SELECT * FROM WhatsAppTemplate WHERE clinicId=? ORDER BY createdAt DESC");$stmt->execute([$user['clinicId']]);send_json($stmt->fetchAll());}
    public function createTemplate($input,$user){$db=$this->db();$id=generate_uuid();$db->prepare("INSERT INTO WhatsAppTemplate(id,clinicId,name,category,language,body,status,purpose) VALUES(?,?,?,?,?,?,?,?)")->execute([$id,$user['clinicId'],$input['name'],$input['category']??'UTILITY',$input['language']??'en',$input['body'],$input['status']??'draft',$input['purpose']??'service']);send_json(['id'=>$id],201);}
    public function automations($input,$user){$db=$this->db();$stmt=$db->prepare("SELECT a.*,t.name templateName FROM WhatsAppAutomation a LEFT JOIN WhatsAppTemplate t ON t.id=a.templateId WHERE a.clinicId=? ORDER BY a.createdAt");$stmt->execute([$user['clinicId']]);send_json($stmt->fetchAll());}
    public function createAutomation($input,$user){$db=$this->db();$this->requireFeature($db,$user['clinicId'],'whatsappAutomationEnabled','WhatsApp automations are not enabled for this clinic.');$id=generate_uuid();$db->prepare("INSERT INTO WhatsAppAutomation(id,clinicId,name,triggerType,triggerValue,templateId,purpose,isActive) VALUES(?,?,?,?,?,?,?,?)")->execute([$id,$user['clinicId'],$input['name'],$input['triggerType'],$input['triggerValue']??null,$input['templateId']??null,$input['purpose']??'service',!empty($input['isActive'])?1:0]);send_json(['id'=>$id],201);}
    public function toggleAutomation($input,$user,$id){$db=$this->db();$this->requireFeature($db,$user['clinicId'],'whatsappAutomationEnabled','WhatsApp automations are not enabled for this clinic.');$db->prepare("UPDATE WhatsAppAutomation SET isActive=? WHERE id=? AND clinicId=?")->execute([!empty($input['isActive'])?1:0,$id,$user['clinicId']]);send_json(['message'=>'Updated']);}
    public function runAutomations($input,$user){$db=$this->db();$c=$user['clinicId'];$this->requireFeature($db,$c,'whatsappAutomationEnabled','WhatsApp automations are not enabled for this clinic.');$settings=$this->settings($db,$c);$stmt=$db->prepare("SELECT a.*,t.name templateName,t.language FROM WhatsAppAutomation a JOIN WhatsAppTemplate t ON t.id=a.templateId WHERE a.clinicId=? AND a.isActive=1 AND a.triggerType IN ('appointment_upcoming','birthday','inactive_days','treatment_completed')");$stmt->execute([$c]);$sent=0;foreach($stmt->fetchAll() as $flow){$clients=[];$context=date('Y-m-d');if($flow['triggerType']==='birthday'){$q=$db->prepare("SELECT * FROM Client WHERE clinicId=? AND status='active' AND substr(dob,6,5)=?");$q->execute([$c,date('m-d')]);$clients=$q->fetchAll();}elseif($flow['triggerType']==='inactive_days'){$days=max(1,intval($flow['triggerValue']));$q=$db->prepare("SELECT * FROM Client WHERE clinicId=? AND status='active' AND lastVisit IS NOT NULL AND lastVisit < ?");$q->execute([$c,date('Y-m-d',strtotime("-$days days"))]);$clients=$q->fetchAll();$context.=":$days";}else{$is2h=$flow['triggerType']==='appointment_upcoming'&&$flow['triggerValue']==='2h';$target=$flow['triggerType']==='appointment_upcoming'&&$flow['triggerValue']==='24h'?date('Y-m-d',strtotime('+1 day')):date('Y-m-d');$status=$flow['triggerType']==='treatment_completed'?'completed':'confirmed';if($is2h){$from=date('H:i',strtotime('+90 minutes'));$to=date('H:i',strtotime('+150 minutes'));$q=$db->prepare("SELECT DISTINCT c.* FROM Client c JOIN Appointment a ON a.clientId=c.id WHERE c.clinicId=? AND c.status='active' AND a.date=? AND a.status=? AND a.startTime BETWEEN ? AND ?");$q->execute([$c,$target,$status,$from,$to]);$context=$target.':2h:'.date('H');}else{$q=$db->prepare("SELECT DISTINCT c.* FROM Client c JOIN Appointment a ON a.clientId=c.id WHERE c.clinicId=? AND c.status='active' AND a.date=? AND a.status=?");$q->execute([$c,$target,$status]);$context=$target.':'.$flow['triggerValue'];}$clients=$q->fetchAll();}foreach($clients as $client)if(whatsapp_automation_dispatch_flow($db,$settings,$flow,$client,$context))$sent++;}send_json(['message'=>'Automation cycle completed','sentCount'=>$sent]);}
    public function campaigns($input,$user){$db=$this->db();$stmt=$db->prepare("SELECT c.*,t.name templateName FROM WhatsAppCampaign c LEFT JOIN WhatsAppTemplate t ON t.id=c.templateId WHERE c.clinicId=? ORDER BY c.createdAt DESC");$stmt->execute([$user['clinicId']]);send_json($stmt->fetchAll());}
    public function createCampaign($input,$user){$db=$this->db();$this->requireFeature($db,$user['clinicId'],'whatsappMarketingEnabled','WhatsApp marketing is not enabled for this clinic.');$id=generate_uuid();$db->prepare("INSERT INTO WhatsAppCampaign(id,clinicId,name,segment,templateId,mediaType,mediaUrl,offerCode,status,scheduledAt) VALUES(?,?,?,?,?,?,?,?,?,?)")->execute([$id,$user['clinicId'],$input['name'],$input['segment'],$input['templateId']??null,$input['mediaType']??'text',$input['mediaUrl']??null,$input['offerCode']??null,$input['status']??'draft',$input['scheduledAt']??null]);send_json(['id'=>$id],201);}
    public function launchCampaign($input,$user,$id){$db=$this->db();$this->requireFeature($db,$user['clinicId'],'whatsappMarketingEnabled','WhatsApp marketing is not enabled for this clinic.');$settings=$this->settings($db,$user['clinicId']);$now=date('H:i');$start=$settings['quietHoursStart']??'21:00';$end=$settings['quietHoursEnd']??'09:00';if(($start<$end&&$now>=$start&&$now<$end)||($start>$end&&($now>=$start||$now<$end)))send_error("Marketing messages are paused during quiet hours ($start to $end).",400);$stmt=$db->prepare("SELECT c.*,t.name templateName,t.language FROM WhatsAppCampaign c LEFT JOIN WhatsAppTemplate t ON t.id=c.templateId WHERE c.id=? AND c.clinicId=?");$stmt->execute([$id,$user['clinicId']]);$campaign=$stmt->fetch();if(!$campaign||!$campaign['templateName'])send_error('Campaign template is required',400);$where=$this->segmentWhere($campaign['segment']);$clients=$db->prepare("SELECT * FROM Client WHERE clinicId=? AND status='active' AND whatsappMarketingOptIn=1 AND phone IS NOT NULL AND ($where)");$clients->execute([$user['clinicId']]);$components=[];if(!empty($campaign['mediaUrl'])&&in_array($campaign['mediaType'],['image','video','document'],true))$components[]=['type'=>'header','parameters'=>[['type'=>$campaign['mediaType'],$campaign['mediaType']=>['link'=>$campaign['mediaUrl']]]]];$sentCount=0;foreach($clients->fetchAll() as $client){$conversation=$this->conversation($db,$user['clinicId'],$client['id']);$sent=meta_whatsapp_send($settings,$client['phone'],$this->templatePayload($campaign['templateName'],$campaign['language']??'en',$components));$db->prepare("INSERT INTO WhatsAppMessage(id,clinicId,conversationId,clientId,direction,purpose,messageType,body,mediaUrl,templateName,metaMessageId,deliveryStatus,sentBy) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)")->execute([generate_uuid(),$user['clinicId'],$conversation['id'],$client['id'],'outbound','marketing','template',$campaign['name'],$campaign['mediaUrl'],$campaign['templateName'],$sent['messageId'],$sent['status'],$user['id']??null]);$sentCount++;}$db->prepare("UPDATE WhatsAppCampaign SET status='sent',sentCount=? WHERE id=? AND clinicId=?")->execute([$sentCount,$id,$user['clinicId']]);send_json(['message'=>'Campaign dispatched','sentCount'=>$sentCount]);}
    public function segments($input,$user){$db=$this->db();$c=$user['clinicId'];$keys=['all','new','returning','vip','birthday','high_spending','inactive_30','inactive_60','inactive_90','inactive_180','dental','aesthetics','implant','orthodontic','skin','laser','membership','branch_based','treatment_based'];$out=[];foreach($keys as $key){$where=$this->segmentWhere($key);$stmt=$db->prepare("SELECT COUNT(*) FROM Client WHERE clinicId=? AND status='active' AND ($where)");$stmt->execute([$c]);$out[]=['id'=>$key,'label'=>ucwords(str_replace('_',' ',$key)),'count'=>intval($stmt->fetchColumn())];}send_json($out);}
    public function health($input,$user){$db=$this->db();$c=$user['clinicId'];$settings=$this->settings($db,$c);$health=meta_whatsapp_health($settings);$queue=$db->prepare("SELECT COUNT(*) FROM WhatsAppQueue WHERE clinicId=? AND status='pending'");$queue->execute([$c]);$logs=$db->prepare("SELECT COUNT(*) FROM WhatsAppWebhookLog WHERE clinicId=? AND status='error'");$logs->execute([$c]);send_json(['connection'=>$health,'pendingQueue'=>intval($queue->fetchColumn()),'failedWebhooks'=>intval($logs->fetchColumn()),'lastWebhookAt'=>$settings['lastWebhookAt']??null,'webhookFailureCount'=>intval($settings['webhookFailureCount']??0),'webhookUrl'=>'/api/v1/whatsapp/webhook']);}
    public function testMessage($input,$user){$db=$this->db();$this->requireFeature($db,$user['clinicId'],'whatsappEnabled','WhatsApp is not enabled for this clinic plan.');$phone=$input['phone']??'';if(!$phone)send_error('Enter your WhatsApp number for the test message.',400);$settings=$this->settings($db,$user['clinicId']);$sent=meta_whatsapp_send($settings,$phone,$this->templatePayload($input['templateName']??'appointment_confirmation',$input['language']??'en'));send_json(['message'=>'Test message queued successfully.','status'=>$sent['status'],'simulation'=>$sent['simulation']]);}
    public function syncTemplates($input,$user){$db=$this->db();$c=$user['clinicId'];$this->requireFeature($db,$c,'whatsappEnabled','WhatsApp is not enabled for this clinic plan.');$remote=meta_whatsapp_templates($this->settings($db,$c));$count=0;foreach(($remote['data']??[]) as $item){$body='';foreach(($item['components']??[]) as $component)if(($component['type']??'')==='BODY')$body=$component['text']??'';$stmt=$db->prepare("SELECT id FROM WhatsAppTemplate WHERE clinicId=? AND name=? AND language=?");$stmt->execute([$c,$item['name'],$item['language']??'en']);$id=$stmt->fetchColumn();if($id)$db->prepare("UPDATE WhatsAppTemplate SET category=?,body=?,status=? WHERE id=?")->execute([$item['category']??'UTILITY',$body,$item['status']??'pending',$id]);else{$id=generate_uuid();$db->prepare("INSERT INTO WhatsAppTemplate(id,clinicId,name,category,language,body,status,purpose) VALUES(?,?,?,?,?,?,?,'service')")->execute([$id,$c,$item['name'],$item['category']??'UTILITY',$item['language']??'en',$body,$item['status']??'pending']);}$count++;}send_json(['message'=>"$count Meta templates synced.",'count'=>$count]);}
    public function updateConversation($input,$user,$clientId){$db=$this->db();$this->assertClientInClinic($db,$clientId,$user['clinicId']);$conversation=$this->conversation($db,$user['clinicId'],$clientId);$db->prepare("UPDATE WhatsAppConversation SET assignedTo=?,internalNote=?,preferredLanguage=? WHERE id=? AND clinicId=?")->execute([$input['assignedTo']??null,$input['internalNote']??null,$input['preferredLanguage']??'en',$conversation['id'],$user['clinicId']]);send_json(['message'=>'Conversation updated.']);}
    public function updateConsent($input,$user,$clientId){$db=$this->db();$optIn=!empty($input['marketingOptIn'])?1:0;$db->prepare("UPDATE Client SET whatsappMarketingOptIn=?,whatsappConsentAt=?,whatsappOptOutAt=? WHERE id=? AND clinicId=?")->execute([$optIn,$optIn?date('Y-m-d H:i:s'):null,$optIn?null:date('Y-m-d H:i:s'),$clientId,$user['clinicId']]);send_json(['message'=>$optIn?'Marketing consent recorded.':'Patient opted out of marketing.']);}
    public function diagnostics($input,$user){$db=$this->db();$stmt=$db->prepare("SELECT * FROM WhatsAppWebhookLog WHERE clinicId=? ORDER BY createdAt DESC LIMIT 20");$stmt->execute([$user['clinicId']]);$queue=$db->prepare("SELECT * FROM WhatsAppQueue WHERE clinicId=? ORDER BY createdAt DESC LIMIT 20");$queue->execute([$user['clinicId']]);send_json(['webhooks'=>$stmt->fetchAll(),'queue'=>$queue->fetchAll()]);}
    public function retryQueue($input,$user){$db=$this->db();$this->requireFeature($db,$user['clinicId'],'whatsappEnabled','WhatsApp is not enabled for this clinic plan.');$stmt=$db->prepare("SELECT * FROM WhatsAppQueue WHERE clinicId=? AND status='pending' ORDER BY createdAt LIMIT 50");$stmt->execute([$user['clinicId']]);$sent=0;foreach($stmt->fetchAll() as $item){try{meta_whatsapp_send($this->settings($db,$user['clinicId']),$item['phone'],json_decode($item['payloadJson'],true));$db->prepare("UPDATE WhatsAppQueue SET status='sent',updatedAt=CURRENT_TIMESTAMP WHERE id=?")->execute([$item['id']]);$sent++;}catch(Exception $e){$db->prepare("UPDATE WhatsAppQueue SET attempts=attempts+1,lastError=?,nextRetryAt=?,updatedAt=CURRENT_TIMESTAMP WHERE id=?")->execute([$e->getMessage(),date('Y-m-d H:i:s',strtotime('+30 minutes')),$item['id']]);}}send_json(['message'=>"$sent queued messages sent.",'sentCount'=>$sent]);}
    public function media($input,$user){$db=$this->db();$stmt=$db->prepare("SELECT * FROM WhatsAppMediaLibrary WHERE clinicId=? AND isApproved=1 ORDER BY createdAt DESC");$stmt->execute([$user['clinicId']]);send_json($stmt->fetchAll());}
    public function branches($input,$user){$db=$this->db();$stmt=$db->prepare("SELECT id,name,phone,whatsappNumber,whatsappPhoneNumberId FROM Branch WHERE clinicId=? AND isActive=1 ORDER BY name");$stmt->execute([$user['clinicId']]);send_json($stmt->fetchAll());}
    public function updateBranch($input,$user,$id){$db=$this->db();$db->prepare("UPDATE Branch SET whatsappNumber=?,whatsappPhoneNumberId=? WHERE id=? AND clinicId=?")->execute([$input['whatsappNumber']??null,$input['whatsappPhoneNumberId']??null,$id,$user['clinicId']]);send_json(['message'=>'Branch routing updated.']);}
    public function settingsGet($input,$user){send_json($this->publicSettings($this->settings($this->db(),$user['clinicId'])));}
    public function settingsSave($input,$user){$db=$this->db();$features=$this->features($db,$user['clinicId']);if(empty($features['whatsappEnabled']))send_error('WhatsApp is not enabled for this clinic plan.',403);$current=$this->settings($db,$user['clinicId']);$token=$current['accessToken']??null;$verifyToken=$current['webhookVerifyToken']??null;$sql=DB_DRIVER==='sqlite'?"INSERT INTO WhatsAppSetting(clinicId,phoneNumberId,businessAccountId,accessToken,webhookVerifyToken,apiVersion,simulationMode,quietHoursStart,quietHoursEnd) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(clinicId) DO UPDATE SET phoneNumberId=excluded.phoneNumberId,businessAccountId=excluded.businessAccountId,accessToken=excluded.accessToken,webhookVerifyToken=excluded.webhookVerifyToken,apiVersion=excluded.apiVersion,simulationMode=excluded.simulationMode,quietHoursStart=excluded.quietHoursStart,quietHoursEnd=excluded.quietHoursEnd,updatedAt=CURRENT_TIMESTAMP":"INSERT INTO WhatsAppSetting(clinicId,phoneNumberId,businessAccountId,accessToken,webhookVerifyToken,apiVersion,simulationMode,quietHoursStart,quietHoursEnd) VALUES(?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE phoneNumberId=VALUES(phoneNumberId),businessAccountId=VALUES(businessAccountId),accessToken=VALUES(accessToken),webhookVerifyToken=VALUES(webhookVerifyToken),apiVersion=VALUES(apiVersion),simulationMode=VALUES(simulationMode),quietHoursStart=VALUES(quietHoursStart),quietHoursEnd=VALUES(quietHoursEnd),updatedAt=CURRENT_TIMESTAMP";$db->prepare($sql)->execute([$user['clinicId'],$input['phoneNumberId']??null,$input['businessAccountId']??null,$token,$verifyToken,$input['apiVersion']??($current['apiVersion']??'v23.0'),!empty($input['simulationMode'])?1:0,$input['quietHoursStart']??'21:00',$input['quietHoursEnd']??'09:00']);send_json(['message'=>'WhatsApp number settings saved. Platform secrets remain superadmin-managed.','hasAccessToken'=>!empty($token)]);}
    public function webhookVerify(){ $db=$this->db();$token=$_GET['hub_verify_token']??'';$challenge=$_GET['hub_challenge']??'';$stmt=$db->prepare("SELECT COUNT(*) FROM WhatsAppSetting WHERE webhookVerifyToken=?");$stmt->execute([$token]);if($token&&$stmt->fetchColumn()){http_response_code(200);echo $challenge;exit;}send_error('Webhook verification failed',403); }
    public function webhook($input){
        $db=$this->db();
        foreach(($input['entry']??[]) as $entry){
            foreach(($entry['changes']??[]) as $change){
                $value=$change['value']??[];
                // Multi-tenant routing: the business phone number that RECEIVED
                // this event tells us which clinic owns it. Never search across
                // clinics by the sender's number — that can cross tenants.
                $phoneNumberId=$value['metadata']['phone_number_id']??'';
                $clinicId=null;
                if($phoneNumberId!==''){
                    $stmt=$db->prepare("SELECT clinicId FROM WhatsAppSetting WHERE phoneNumberId=? LIMIT 1");
                    $stmt->execute([$phoneNumberId]);
                    $clinicId=$stmt->fetchColumn() ?: null;
                }
                if(!$clinicId){
                    // Unknown business number — cannot attribute safely. Log and skip.
                    $db->prepare("INSERT INTO WhatsAppWebhookLog(id,clinicId,eventType,status,details) VALUES(?,?,'message_event','unrouted',?)")
                       ->execute([generate_uuid(),null,json_encode(['phoneNumberId'=>$phoneNumberId])]);
                    continue;
                }
                // Delivery status updates — scoped to this clinic
                foreach(($value['statuses']??[]) as $status){
                    $db->prepare("UPDATE WhatsAppMessage SET deliveryStatus=? WHERE metaMessageId=? AND clinicId=?")
                       ->execute([$status['status']??'sent',$status['id']??'',$clinicId]);
                }
                // Inbound messages — match the patient WITHIN this clinic only
                foreach(($value['messages']??[]) as $message){
                    $phone=$message['from']??'';
                    $stmt=$db->prepare("SELECT * FROM Client WHERE clinicId=? AND REPLACE(REPLACE(REPLACE(phone,'+',''),' ',''),'-','') LIKE ? LIMIT 1");
                    $stmt->execute([$clinicId,'%'.substr($phone,-10)]);
                    $client=$stmt->fetch();
                    if(!$client)continue;
                    $conversation=$this->conversation($db,$clinicId,$client['id']);
                    $body=$message['text']['body']??'Incoming WhatsApp message';
                    $db->prepare("INSERT INTO WhatsAppMessage(id,clinicId,conversationId,clientId,direction,purpose,messageType,body,metaMessageId,deliveryStatus) VALUES(?,?,?,?,?,?,?,?,?,?)")
                       ->execute([generate_uuid(),$clinicId,$conversation['id'],$client['id'],'inbound','support',$message['type']??'text',$body,$message['id']??null,'received']);
                    $db->prepare("UPDATE WhatsAppConversation SET freeReplyUntil=?,lastMessageAt=CURRENT_TIMESTAMP WHERE id=?")
                       ->execute([date('Y-m-d H:i:s',strtotime('+24 hours')),$conversation['id']]);
                    if(in_array(strtoupper(trim($body)),['STOP','UNSUBSCRIBE','OPT OUT'],true))
                        $db->prepare("UPDATE Client SET whatsappMarketingOptIn=0,whatsappOptOutAt=CURRENT_TIMESTAMP WHERE id=?")->execute([$client['id']]);
                }
                $db->prepare("UPDATE WhatsAppSetting SET lastWebhookAt=CURRENT_TIMESTAMP,lastWebhookError=NULL WHERE clinicId=?")->execute([$clinicId]);
                $db->prepare("INSERT INTO WhatsAppWebhookLog(id,clinicId,eventType,status,details) VALUES(?,?,'message_event','received',?)")->execute([generate_uuid(),$clinicId,json_encode($value)]);
            }
        }
        send_json(['received'=>true]);
    }
}
