import { useEffect, useMemo, useState } from 'react';
import {
  ArrowRight, CalendarDays, Check, CheckCircle2, ChevronDown, Clock3, ExternalLink,
  Facebook, HeartPulse, Instagram, Loader2, Mail, MapPin, Menu, Phone, Play,
  ShieldCheck, Sparkles, Star, Stethoscope, X, Youtube,
} from 'lucide-react';
import ClinicLogoMark from '../components/branding/ClinicLogoMark';
import { fetchPublicApi } from '../config/api';

const money = (value) => `PKR ${Number(value || 0).toLocaleString()}`;
const today = new Date().toISOString().slice(0, 10);
const digits = (value = '') => value.replace(/\D/g, '');
const whatsappUrl = (phone, text) => `https://wa.me/${digits(phone)}?text=${encodeURIComponent(text)}`;
const sectionOn = (config, key) => config.sections?.[key] !== false;
const sectionStyle = (config, key) => ({ order: (config.sectionOrder || []).indexOf(key) + 2 || 20 });

function SectionTitle({ eyebrow, title, text, center = false }) {
  return <div className={center ? 'max-w-2xl mx-auto text-center' : 'max-w-2xl'}>
    <p className="text-[11px] font-black uppercase tracking-[0.22em] text-teal-700">{eyebrow}</p>
    <h2 className="mt-3 text-3xl sm:text-4xl font-black tracking-tight text-slate-950">{title}</h2>
    {text && <p className="mt-3 text-sm sm:text-base leading-7 text-slate-600">{text}</p>}
  </div>;
}

function DoctorModal({ doctor, clinic, onClose }) {
  const [date, setDate] = useState('');
  const [slots, setSlots] = useState([]);
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    if (!doctor || !date) return setSlots([]);
    setLoading(true);
    fetchPublicApi(`/public/availability?staffId=${doctor.id}&branchId=${doctor.branchId || ''}&date=${date}&duration=30`)
      .then((data) => setSlots(data.slots || [])).finally(() => setLoading(false));
  }, [doctor, date]);
  if (!doctor) return null;
  return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/60 p-4 backdrop-blur-sm">
    <div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-[28px] bg-white p-6 shadow-2xl">
      <div className="flex justify-between gap-4"><div className="flex gap-3"><div className="flex h-16 w-16 items-center justify-center rounded-2xl text-lg font-black text-white" style={{ background: doctor.avatarColor }}>{doctor.avatar || doctor.name.slice(0, 2)}</div><div><h3 className="text-xl font-black">{doctor.name}</h3><p className="text-sm font-bold text-teal-700">{doctor.designation || doctor.role}</p><p className="mt-1 flex gap-1 text-xs text-amber-600"><Star className="h-3.5 w-3.5 fill-current" />{doctor.rating}</p></div></div><button onClick={onClose}><X /></button></div>
      <p className="mt-5 text-sm leading-6 text-slate-600">{doctor.bio || 'Dedicated to thoughtful, evidence-based patient care.'}</p>
      <div className="mt-4 grid grid-cols-2 gap-3 text-xs"><div className="rounded-xl bg-slate-50 p-3"><b>Qualifications</b><p className="mt-1 text-slate-500">{doctor.qualifications || 'Clinical specialist'}</p></div><div className="rounded-xl bg-slate-50 p-3"><b>Experience</b><p className="mt-1 text-slate-500">{doctor.experience || 'Experienced clinician'}</p></div></div>
      <p className="mt-4 text-xs font-bold text-slate-500">{doctor.workingDays} · {doctor.workingHours}</p>
      <label className="mt-5 block text-xs font-bold text-slate-600">Check available slots<input type="date" min={today} value={date} onChange={(e) => setDate(e.target.value)} className="public-input" /></label>
      <div className="mt-3 flex flex-wrap gap-2">{loading ? <Loader2 className="h-5 w-5 animate-spin text-teal-700" /> : slots.slice(0, 8).map((slot) => <span key={slot.startTime} className="rounded-lg bg-teal-50 px-3 py-2 text-xs font-bold text-teal-800">{slot.startTime}</span>)}</div>
      <a href="#book" onClick={onClose} className="mt-5 flex justify-center rounded-xl bg-teal-900 px-4 py-3 text-sm font-black text-white">Book with {doctor.name}</a>
    </div>
  </div>;
}

function BookingForm({ site }) {
  const { clinic, config, services, staff, branches } = site;
  const [form, setForm] = useState({ serviceIds: [], staffId: '', branchId: branches[0]?.id || '', date: '', startTime: '', name: '', phone: '', email: '', dob: '', gender: '', notes: '' });
  const [slots, setSlots] = useState([]), [loadingSlots, setLoadingSlots] = useState(false), [submitting, setSubmitting] = useState(false), [result, setResult] = useState(null), [error, setError] = useState('');
  const selected = services.filter((service) => form.serviceIds.includes(service.id));
  const duration = selected.reduce((sum, service) => sum + Number(service.duration), 0);
  const total = selected.reduce((sum, service) => sum + Number(service.price), 0);
  const selectedSpecialties = [...new Set(selected.map((service) => service.specialty))];
  const doctors = staff.filter((doctor) => (!form.branchId || doctor.branchId === form.branchId) && (!selectedSpecialties.length || selectedSpecialties.includes(doctor.specialty)));
  const step = result ? 5 : !form.serviceIds.length ? 1 : !form.staffId ? 2 : !form.startTime ? 3 : 4;
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value, ...(['staffId', 'date', 'branchId'].includes(key) ? { startTime: '' } : {}), ...(key === 'branchId' ? { staffId: '' } : {}) }));
  const toggleService = (id) => set('serviceIds', form.serviceIds.includes(id) ? form.serviceIds.filter((serviceId) => serviceId !== id) : [...form.serviceIds, id]);
  useEffect(() => {
    const selectOfferService = (event) => {
      if (event.detail && !form.serviceIds.includes(event.detail)) set('serviceIds', [...form.serviceIds, event.detail]);
    };
    window.addEventListener('select-public-service', selectOfferService);
    return () => window.removeEventListener('select-public-service', selectOfferService);
  }, [form.serviceIds]);
  useEffect(() => {
    if (!form.staffId || !form.date || !duration) return setSlots([]);
    setLoadingSlots(true);
    fetchPublicApi(`/public/availability?staffId=${form.staffId}&branchId=${form.branchId}&date=${form.date}&duration=${duration}`).then((data) => setSlots(data.slots || [])).catch((err) => setError(err.message)).finally(() => setLoadingSlots(false));
  }, [form.staffId, form.branchId, form.date, duration]);
  const submit = async (event) => { event.preventDefault(); setError(''); if (!form.serviceIds.length) return setError('Please choose at least one service.'); if (!form.startTime) return setError('Please select an available time slot.'); setSubmitting(true); try { setResult(await fetchPublicApi('/public/book', { method: 'POST', body: JSON.stringify(form) })); } catch (err) { setError(err.message); } finally { setSubmitting(false); } };
  const summary = <div className="rounded-2xl bg-slate-50 p-4"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">Booking summary</p>{selected.length ? <><div className="mt-2 space-y-1">{selected.map((service) => <p key={service.id} className="flex justify-between text-xs"><span>{service.name}</span><b>{money(service.price)}</b></p>)}</div><p className="mt-3 border-t border-slate-200 pt-2 text-xs font-black text-teal-900">{selected.length} services · {duration} min · {money(total)}</p></> : <p className="mt-2 text-xs text-slate-400">Select services to see your estimate.</p>}</div>;
  if (result) return <div className="rounded-[28px] border border-teal-900/10 bg-white p-7 shadow-2xl"><CheckCircle2 className="h-12 w-12 text-teal-700" /><h3 className="mt-5 text-2xl font-black">Appointment request received.</h3><p className="mt-2 text-sm leading-6 text-slate-600">Reference: <strong>{result.reference}</strong>. Our team can contact you at {form.phone}.</p><div className="mt-5 rounded-2xl bg-teal-50 p-4 text-sm text-teal-900"><strong>{money(result.total)}</strong> · {result.duration} minutes · {form.date} at {form.startTime}</div><a target="_blank" rel="noreferrer" href={whatsappUrl(clinic.whatsapp, `Assalam-o-Alaikum, my booking reference is ${result.reference}. Please confirm my appointment.`)} className="mt-4 flex justify-center rounded-xl bg-green-600 px-4 py-3 text-sm font-black text-white">Confirm on WhatsApp</a></div>;
  return <form onSubmit={submit} className="rounded-[28px] border border-teal-900/10 bg-white p-5 shadow-2xl sm:p-7">
    <div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-teal-900 text-white"><CalendarDays className="h-5 w-5" /></div><div><h3 className="font-black">Book your appointment</h3><p className="text-xs text-slate-500">{config.bookingNote}</p></div></div>
    <div className="mt-5 grid grid-cols-5 gap-1">{['Services', 'Doctor', 'Slot', 'Details', 'Done'].map((label, index) => <div key={label} className={`rounded-lg px-1 py-2 text-center text-[9px] font-black ${step >= index + 1 ? 'bg-teal-900 text-white' : 'bg-slate-100 text-slate-400'}`}>{index + 1}. {label}</div>)}</div>
    <p className="mt-5 text-xs font-black uppercase tracking-wider text-slate-500">1. Choose services</p><div className="mt-2 max-h-48 space-y-2 overflow-y-auto pr-1">{services.map((service) => <label key={service.id} className={`flex cursor-pointer items-center justify-between gap-3 rounded-xl border p-3 ${form.serviceIds.includes(service.id) ? 'border-teal-700 bg-teal-50' : 'border-slate-200'}`}><span className="flex gap-2"><input type="checkbox" checked={form.serviceIds.includes(service.id)} onChange={() => toggleService(service.id)} /><span><b className="block text-xs">{service.name}</b><span className="text-[11px] text-slate-500">{service.category} · {service.duration} min</span></span></span><b className="text-xs text-teal-800">{money(service.price)}</b></label>)}</div>
    <div className="mt-4">{summary}</div>
    <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">Branch<select value={form.branchId} onChange={(e) => set('branchId', e.target.value)} className="public-input">{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label><label className="text-xs font-bold text-slate-600">Relevant doctor<select required value={form.staffId} onChange={(e) => set('staffId', e.target.value)} className="public-input"><option value="">Select doctor</option>{doctors.map((doctor) => <option key={doctor.id} value={doctor.id}>{doctor.name} · {doctor.specialty}</option>)}</select></label><label className="text-xs font-bold text-slate-600">Date<input required type="date" min={today} value={form.date} onChange={(e) => set('date', e.target.value)} className="public-input" /></label></div>
    <p className="mt-4 text-xs font-bold text-slate-600">Available slots</p><div className="mt-2 flex min-h-9 flex-wrap gap-2">{loadingSlots ? <Loader2 className="h-5 w-5 animate-spin text-teal-700" /> : slots.map((slot) => <button type="button" key={slot.startTime} onClick={() => set('startTime', slot.startTime)} className={`rounded-lg px-3 py-2 text-xs font-bold ${form.startTime === slot.startTime ? 'bg-teal-800 text-white' : 'bg-slate-100 text-slate-600'}`}>{slot.startTime}</button>)}</div>
    <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">Full name<input required value={form.name} onChange={(e) => set('name', e.target.value)} className="public-input" /></label><label className="text-xs font-bold text-slate-600">Phone<input required value={form.phone} onChange={(e) => set('phone', e.target.value)} className="public-input" /></label><label className="text-xs font-bold text-slate-600">Email<input type="email" value={form.email} onChange={(e) => set('email', e.target.value)} className="public-input" /></label><label className="text-xs font-bold text-slate-600">Date of birth<input type="date" value={form.dob} onChange={(e) => set('dob', e.target.value)} className="public-input" /></label></div>
    <label className="mt-3 block text-xs font-bold text-slate-600">Notes<textarea rows={2} value={form.notes} onChange={(e) => set('notes', e.target.value)} className="public-input resize-none" /></label>{error && <p className="mt-3 rounded-xl bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700">{error}</p>}<button disabled={submitting} className="mt-4 flex w-full justify-center gap-2 rounded-xl bg-teal-900 px-4 py-3 text-sm font-black text-white">{submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : <ArrowRight className="h-4 w-4" />} Request appointment</button>
  </form>;
}

export default function PublicSite() {
  const [site, setSite] = useState(null), [error, setError] = useState(''), [menu, setMenu] = useState(false), [activeCategory, setActiveCategory] = useState('All'), [doctor, setDoctor] = useState(null), [faq, setFaq] = useState(0);
  useEffect(() => { fetchPublicApi('/public/site').then(setSite).catch((err) => setError(err.message)); }, []);
  useEffect(() => {
    if (!site) return;
    document.title = site.config.seoTitle || `${site.clinic.name} - Clinic`;
    document.querySelector('meta[name="description"]')?.setAttribute('content', site.config.seoDescription || site.clinic.tagline || '');
    let og = document.querySelector('meta[property="og:image"]');
    if (!og) { og = document.createElement('meta'); og.setAttribute('property', 'og:image'); document.head.appendChild(og); }
    og.setAttribute('content', site.config.ogImage || site.config.heroImage || '');
  }, [site]);
  const categories = useMemo(() => ['All', ...new Set((site?.services || []).map((service) => service.category).filter(Boolean))], [site]);
  if (!site) return <div className="flex min-h-screen items-center justify-center bg-[#f8f7f2]">{error || <Loader2 className="h-8 w-8 animate-spin text-teal-800" />}</div>;
  const { clinic, config, services, staff, testimonials, gallery } = site, nav = config.nav || [], filteredServices = activeCategory === 'All' ? services : services.filter((service) => service.category === activeCategory);
  const wa = whatsappUrl(clinic.whatsapp, `Assalam-o-Alaikum, I want to book an appointment at ${clinic.name}.`);
  const socials = [[Facebook, config.socials?.facebook], [Instagram, config.socials?.instagram], [Play, config.socials?.tiktok], [Youtube, config.socials?.youtube]];
  return <div className="public-site min-h-screen bg-[#f8f7f2] pb-16 text-slate-900 md:pb-0">
    <DoctorModal doctor={doctor} clinic={clinic} onClose={() => setDoctor(null)} />
    {config.announcement && <div className="bg-teal-950 px-4 py-2 text-center text-[11px] font-bold text-teal-50">{config.announcement}</div>}
    <header className="sticky top-0 z-50 border-b border-black/5 bg-[#f8f7f2]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3"><a href="#home" className="flex items-center gap-2.5"><ClinicLogoMark logo={clinic.logo} className="flex h-10 w-10 items-center justify-center overflow-hidden rounded-xl bg-teal-900 font-black text-white" /><span><b className="block text-sm">{clinic.name}</b><span className="text-[10px] text-slate-500">{clinic.tagline}</span></span></a><nav className="hidden items-center gap-5 md:flex">{nav.map((item) => <a key={item.href} href={item.href} className={`text-xs font-bold ${item.href === '#book' ? 'rounded-full bg-teal-900 px-4 py-2.5 text-white' : 'text-slate-600'}`}>{item.label}</a>)}</nav><button className="md:hidden" onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button></div>{menu && <nav className="flex flex-col border-t px-5 py-2 md:hidden">{nav.map((item) => <a key={item.href} href={item.href} onClick={() => setMenu(false)} className="py-2 text-sm font-bold">{item.label}</a>)}</nav>}</header>
    <main className="flex flex-col">
      <section id="home" className="overflow-hidden"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-24"><div><p className="inline-flex gap-2 rounded-full border bg-white/70 px-3 py-1.5 text-[11px] font-bold text-teal-900"><Sparkles className="h-3.5 w-3.5" />{config.eyebrow}</p><h1 className="mt-6 text-5xl font-black leading-[1.03] tracking-[-0.055em] sm:text-7xl">{config.heroTitle}</h1><p className="mt-5 max-w-xl leading-7 text-slate-600">{config.heroSubtitle}</p><div className="mt-7 flex gap-3"><a href="#book" className="rounded-full bg-teal-900 px-5 py-3 text-sm font-black text-white">Book now</a><a href="#services" className="rounded-full border bg-white px-5 py-3 text-sm font-black">Explore care</a></div><div className="mt-8 flex flex-wrap gap-4 text-xs font-bold text-slate-600"><span className="flex gap-2"><Star className="h-4 w-4 fill-amber-400 text-amber-400" />4.9 patient rating</span><span className="flex gap-2"><ShieldCheck className="h-4 w-4 text-teal-700" />Secure booking</span><span className="flex gap-2"><Clock3 className="h-4 w-4 text-teal-700" />{config.hours}</span></div></div><div className="aspect-[4/4.4] overflow-hidden rounded-[36px] bg-teal-900 shadow-2xl">{config.heroImage ? <img src={config.heroImage} className="h-full w-full object-cover" /> : <HeartPulse className="m-auto h-full w-32 text-white" />}</div></div></section>
      <section className="border-y bg-white"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-3 px-5 py-5 md:grid-cols-4">{[['Experienced Doctors', 'Qualified specialists'], ['Transparent Pricing', 'No hidden surprises'], ['Secure Records', 'Privacy-first care'], ['Easy Booking', 'Online in minutes']].map(([title, text]) => <div key={title}><b className="text-xs text-teal-900">{title}</b><p className="text-[11px] text-slate-500">{text}</p></div>)}</div></section>
      {sectionOn(config, 'offers') && !!config.offers?.length && <section style={sectionStyle(config, 'offers')} className="overflow-hidden bg-teal-950 py-4 text-white"><div className="public-offer-track flex w-max gap-3 px-3">{[...config.offers, ...config.offers].map((offer, index) => <a href="#book" onClick={() => offer.serviceId && window.dispatchEvent(new CustomEvent('select-public-service', { detail: offer.serviceId }))} key={`${offer.title}-${index}`} className="w-80 rounded-2xl border border-white/10 bg-white/10 p-4"><p className="text-[10px] font-black uppercase tracking-wider text-rose-200">{offer.badge} · until {offer.expiry || 'limited time'}</p><b className="mt-1 block text-sm">{offer.title}</b><p className="mt-1 text-xs text-white/60">{offer.description}</p><p className="mt-2 text-xs"><s className="text-white/50">{money(offer.oldPrice)}</s> <b className="ml-2 text-rose-200">{money(offer.price)}</b></p></a>)}</div></section>}
      {sectionOn(config, 'services') && <section style={sectionStyle(config, 'services')} id="services" className="mx-auto max-w-7xl px-5 py-20"><SectionTitle eyebrow="Services & pricing" title="Care for every part of your wellbeing." text="Explore general clinic, skin aesthetics, and dental treatments with clear prices." /><div className="mt-6 flex flex-wrap gap-2">{categories.map((category) => <button key={category} onClick={() => setActiveCategory(category)} className={`rounded-full px-3 py-2 text-xs font-bold transition ${activeCategory === category ? 'bg-teal-900 text-white' : 'bg-white text-slate-600 shadow-sm'}`}>{category}</button>)}</div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{filteredServices.map((service) => <a href="#book" key={service.id} className="rounded-2xl border border-black/5 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><Stethoscope className="h-5 w-5 text-teal-700" /><h3 className="mt-4 font-black">{service.name}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{service.description || service.specialty}</p><div className="mt-4 flex justify-between border-t pt-3 text-xs"><b className="text-teal-800">{money(service.price)}</b><span>{service.duration} min</span></div></a>)}</div></section>}
      {sectionOn(config, 'doctors') && <section style={sectionStyle(config, 'doctors')} id="doctors" className="bg-white/70 py-20"><div className="mx-auto max-w-7xl px-5"><SectionTitle center eyebrow="Our team" title="Meet your care specialists." /><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{staff.filter((item) => !['Receptionist', 'Manager', 'Dental Assistant'].includes(item.role)).map((item) => <button onClick={() => setDoctor(item)} key={item.id} className="rounded-2xl border bg-white p-5 text-left shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="flex gap-3"><div className="flex h-14 w-14 items-center justify-center rounded-2xl font-black text-white" style={{ background: item.avatarColor }}>{item.avatar}</div><div><b>{item.name}</b><p className="text-xs font-bold text-teal-700">{item.designation || item.role}</p><p className="mt-1 text-[11px] text-amber-600">★ {item.rating}</p></div></div><p className="mt-3 text-xs leading-5 text-slate-500">{item.bio || item.qualifications}</p><span className="mt-3 block text-[11px] font-bold text-teal-700">View profile & availability →</span></button>)}</div></div></section>}
      {sectionOn(config, 'gallery') && !!gallery?.length && <section style={sectionStyle(config, 'gallery')} id="gallery" className="mx-auto max-w-7xl px-5 py-20"><SectionTitle eyebrow="Clinic gallery" title="A calm, premium care environment." /><div className="mt-8 flex snap-x gap-4 overflow-x-auto pb-3">{gallery.map((item) => <figure key={item.id} className="min-w-[280px] snap-start overflow-hidden rounded-2xl bg-white shadow-sm"><img src={item.imageUrl} className="h-52 w-full object-cover" /><figcaption className="p-3 text-xs font-bold text-slate-600">{item.service || item.notes}</figcaption></figure>)}</div></section>}
      {sectionOn(config, 'testimonials') && !!testimonials?.length && <section style={sectionStyle(config, 'testimonials')} id="reviews" className="bg-teal-950 py-20 text-white"><div className="mx-auto max-w-7xl px-5"><SectionTitle eyebrow="Patient stories" title="Care people feel good about." /><div className="mt-8 grid gap-4 md:grid-cols-3">{testimonials.slice(0, 6).map((item) => <div key={item.id} className="rounded-2xl border border-white/10 bg-white/10 p-5"><p className="text-amber-300">{'★'.repeat(Number(item.overallRating))}</p><p className="mt-3 text-sm leading-6 text-white/80">“{item.comment}”</p><b className="mt-4 block text-xs">{item.clientName}</b><span className="text-[11px] text-white/50">{item.serviceName || item.staffName}</span></div>)}</div></div></section>}
      {sectionOn(config, 'about') && <section style={sectionStyle(config, 'about')} id="about" className="mx-auto max-w-7xl px-5 py-20"><SectionTitle eyebrow="About us" title={config.aboutTitle} text={config.aboutText} /></section>}
      {sectionOn(config, 'faq') && <section style={sectionStyle(config, 'faq')} className="mx-auto max-w-4xl px-5 pb-20"><SectionTitle eyebrow="FAQs" title="Questions, answered clearly." /><div className="mt-6 space-y-2">{(config.faqs || []).map((item, index) => <button key={index} onClick={() => setFaq(faq === index ? -1 : index)} className="w-full rounded-xl border bg-white p-4 text-left"><span className="flex justify-between text-sm font-black">{item.question}<ChevronDown className={`h-4 w-4 transition ${faq === index ? 'rotate-180' : ''}`} /></span>{faq === index && <p className="mt-2 text-xs leading-5 text-slate-500">{item.answer}</p>}</button>)}</div></section>}
      {sectionOn(config, 'map') && <section style={sectionStyle(config, 'map')} className="bg-white py-16"><div className="mx-auto grid max-w-7xl gap-6 px-5 lg:grid-cols-2"><div><SectionTitle eyebrow="Visit us" title="Find your nearest clinic." text={clinic.address} /><a target="_blank" rel="noreferrer" href={config.googleMapsUrl} className="mt-5 inline-flex gap-2 rounded-full bg-teal-900 px-5 py-3 text-sm font-black text-white">Get directions <ExternalLink className="h-4 w-4" /></a>{config.googleBusinessUrl && <a target="_blank" rel="noreferrer" href={config.googleBusinessUrl} className="ml-3 text-xs font-black text-teal-800">Google profile</a>}</div><iframe title="Clinic location" className="h-64 w-full rounded-2xl border-0" loading="lazy" src={`https://maps.google.com/maps?q=${encodeURIComponent(clinic.address)}&output=embed`} /></div></section>}
      {sectionOn(config, 'booking') && <section style={sectionStyle(config, 'booking')} id="book" className="bg-gradient-to-br from-teal-950 to-slate-900 py-20"><div className="mx-auto grid max-w-7xl gap-9 px-5 lg:grid-cols-[.85fr_1.15fr]"><div className="text-white"><p className="text-[11px] font-black uppercase tracking-widest text-teal-200">Online booking</p><h2 className="mt-3 text-4xl font-black">Plan your visit in a few calm steps.</h2><p className="mt-4 text-sm leading-7 text-white/70">{config.bookingNote}</p></div><BookingForm site={site} /></div></section>}
    </main>
    <footer className="mx-auto grid max-w-7xl gap-5 px-5 py-10 sm:grid-cols-3"><div><b>{clinic.name}</b><p className="mt-2 text-xs text-slate-500">{clinic.tagline}</p></div><div className="space-y-2 text-xs text-slate-600"><p className="flex gap-2"><MapPin className="h-4 w-4" />{clinic.address}</p><p className="flex gap-2"><Phone className="h-4 w-4" />{clinic.phone}</p><p className="flex gap-2"><Mail className="h-4 w-4" />{clinic.email}</p></div><div className="flex gap-3 sm:justify-end">{socials.filter(([, href]) => href).map(([Icon, href]) => <a key={href} href={href}><Icon className="h-5 w-5 text-teal-800" /></a>)}</div></footer>
    <a href={wa} target="_blank" rel="noreferrer" className="fixed bottom-20 right-4 z-50 rounded-full bg-green-600 px-4 py-3 text-xs font-black text-white shadow-xl md:bottom-5">WhatsApp</a>
    <div className="fixed inset-x-0 bottom-0 z-40 grid grid-cols-2 gap-2 border-t bg-white/95 p-2 shadow-xl backdrop-blur md:hidden"><a href={`tel:${clinic.phone}`} className="rounded-xl border border-teal-900 px-3 py-3 text-center text-xs font-black text-teal-900">Call now</a><a href="#book" className="rounded-xl bg-teal-900 px-3 py-3 text-center text-xs font-black text-white">Book appointment</a></div>
  </div>;
}
