CREATE TABLE IF NOT EXISTS `PublicSiteConfig` (
  `clinicId` VARCHAR(36) NOT NULL,
  `configJson` LONGTEXT NOT NULL,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`clinicId`),
  CONSTRAINT `FK_PublicSiteConfig_Clinic` FOREIGN KEY (`clinicId`) REFERENCES `Clinic` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
