CREATE TABLE IF NOT EXISTS WhatsAppSetting (clinicId TEXT PRIMARY KEY, phoneNumberId TEXT, businessAccountId TEXT, accessToken TEXT, webhookVerifyToken TEXT, apiVersion TEXT DEFAULT 'v23.0', simulationMode INTEGER DEFAULT 1, currency TEXT DEFAULT 'PKR', updatedAt TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS WhatsAppTemplate (id TEXT PRIMARY KEY, clinicId TEXT NOT NULL, name TEXT NOT NULL, category TEXT NOT NULL, language TEXT DEFAULT 'en', messageType TEXT DEFAULT 'template', body TEXT NOT NULL, status TEXT DEFAULT 'draft', purpose TEXT DEFAULT 'service', createdAt TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS WhatsAppConversation (id TEXT PRIMARY KEY, clinicId TEXT NOT NULL, clientId TEXT NOT NULL, status TEXT DEFAULT 'open', assignedTo TEXT, lastMessageAt TEXT DEFAULT CURRENT_TIMESTAMP, unreadCount INTEGER DEFAULT 0, createdAt TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX IF NOT EXISTS UX_WhatsAppConversation_Client ON WhatsAppConversation(clinicId, clientId);
CREATE TABLE IF NOT EXISTS WhatsAppMessage (id TEXT PRIMARY KEY, clinicId TEXT NOT NULL, conversationId TEXT NOT NULL, clientId TEXT NOT NULL, direction TEXT NOT NULL, purpose TEXT DEFAULT 'support', messageType TEXT DEFAULT 'text', body TEXT, mediaUrl TEXT, templateName TEXT, metaMessageId TEXT, deliveryStatus TEXT DEFAULT 'queued', sentBy TEXT, cost REAL DEFAULT 0, createdAt TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS WhatsAppAutomation (id TEXT PRIMARY KEY, clinicId TEXT NOT NULL, name TEXT NOT NULL, triggerType TEXT NOT NULL, triggerValue TEXT, actionType TEXT DEFAULT 'send_template', templateId TEXT, purpose TEXT DEFAULT 'service', isActive INTEGER DEFAULT 1, createdAt TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS WhatsAppCampaign (id TEXT PRIMARY KEY, clinicId TEXT NOT NULL, name TEXT NOT NULL, segment TEXT NOT NULL, templateId TEXT, mediaType TEXT DEFAULT 'text', mediaUrl TEXT, offerCode TEXT, status TEXT DEFAULT 'draft', scheduledAt TEXT, sentCount INTEGER DEFAULT 0, deliveredCount INTEGER DEFAULT 0, readCount INTEGER DEFAULT 0, responseCount INTEGER DEFAULT 0, conversionCount INTEGER DEFAULT 0, revenue REAL DEFAULT 0, createdAt TEXT DEFAULT CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO WhatsAppSetting (clinicId, simulationMode) VALUES ('clinic-smile-expert-001', 1);
INSERT OR IGNORE INTO WhatsAppTemplate (id,clinicId,name,category,body,status,purpose) VALUES
('wat-001','clinic-smile-expert-001','appointment_confirmation','UTILITY','Assalam-o-Alaikum {{name}}, your appointment at {{clinic}} is confirmed for {{date}} at {{time}}. Reply if you need help.','approved','appointment'),
('wat-002','clinic-smile-expert-001','appointment_reminder_24h','UTILITY','Reminder: your appointment at {{clinic}} is tomorrow at {{time}}. Reply C to confirm or R to reschedule.','approved','appointment'),
('wat-003','clinic-smile-expert-001','post_treatment_aftercare','UTILITY','Assalam-o-Alaikum {{name}}, we hope you are comfortable after your treatment. Please follow the care instructions shared by your clinician.','approved','clinical'),
('wat-004','clinic-smile-expert-001','birthday_treatment_offer','MARKETING','Happy birthday {{name}}. Enjoy a special birthday treatment offer from {{clinic}}. Reply BOOK to reserve your visit.','approved','marketing'),
('wat-005','clinic-smile-expert-001','inactive_patient_reactivation','MARKETING','We miss you, {{name}}. Your care team at {{clinic}} would be happy to schedule your next review. Reply BOOK for available slots.','approved','marketing'),
('wat-006','clinic-smile-expert-001','payment_reminder','UTILITY','Assalam-o-Alaikum {{name}}, your pending balance is PKR {{balance}}. Contact {{clinic}} if you need billing support.','approved','billing');
INSERT OR IGNORE INTO WhatsAppAutomation (id,clinicId,name,triggerType,triggerValue,templateId,purpose,isActive) VALUES
('waa-001','clinic-smile-expert-001','Appointment booked confirmation','appointment_booked','immediate','wat-001','appointment',1),
('waa-002','clinic-smile-expert-001','Appointment reminder','appointment_upcoming','24h','wat-002','appointment',1),
('waa-003','clinic-smile-expert-001','Post-treatment care','treatment_completed','2h','wat-003','clinical',1),
('waa-004','clinic-smile-expert-001','Birthday treatment offer','birthday','same_day','wat-004','marketing',1),
('waa-005','clinic-smile-expert-001','Inactive patient reactivation','inactive_days','90','wat-005','marketing',1);
