CREATE TABLE IF NOT EXISTS WhatsAppSetting (clinicId VARCHAR(64) PRIMARY KEY, phoneNumberId VARCHAR(120), businessAccountId VARCHAR(120), accessToken TEXT, webhookVerifyToken VARCHAR(255), apiVersion VARCHAR(20) DEFAULT 'v23.0', simulationMode TINYINT DEFAULT 1, currency VARCHAR(10) DEFAULT 'PKR', updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS WhatsAppTemplate (id VARCHAR(64) PRIMARY KEY, clinicId VARCHAR(64) NOT NULL, name VARCHAR(180) NOT NULL, category VARCHAR(30) NOT NULL, language VARCHAR(20) DEFAULT 'en', messageType VARCHAR(30) DEFAULT 'template', body TEXT NOT NULL, status VARCHAR(30) DEFAULT 'draft', purpose VARCHAR(30) DEFAULT 'service', createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS WhatsAppConversation (id VARCHAR(64) PRIMARY KEY, clinicId VARCHAR(64) NOT NULL, clientId VARCHAR(64) NOT NULL, status VARCHAR(30) DEFAULT 'open', assignedTo VARCHAR(64), lastMessageAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, unreadCount INT DEFAULT 0, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY UX_WhatsAppConversation_Client (clinicId, clientId));
CREATE TABLE IF NOT EXISTS WhatsAppMessage (id VARCHAR(64) PRIMARY KEY, clinicId VARCHAR(64) NOT NULL, conversationId VARCHAR(64) NOT NULL, clientId VARCHAR(64) NOT NULL, direction VARCHAR(20) NOT NULL, purpose VARCHAR(30) DEFAULT 'support', messageType VARCHAR(30) DEFAULT 'text', body TEXT, mediaUrl TEXT, templateName VARCHAR(180), metaMessageId VARCHAR(255), deliveryStatus VARCHAR(30) DEFAULT 'queued', sentBy VARCHAR(64), cost DECIMAL(12,4) DEFAULT 0, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS WhatsAppAutomation (id VARCHAR(64) PRIMARY KEY, clinicId VARCHAR(64) NOT NULL, name VARCHAR(180) NOT NULL, triggerType VARCHAR(80) NOT NULL, triggerValue VARCHAR(120), actionType VARCHAR(80) DEFAULT 'send_template', templateId VARCHAR(64), purpose VARCHAR(30) DEFAULT 'service', isActive TINYINT DEFAULT 1, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS WhatsAppCampaign (id VARCHAR(64) PRIMARY KEY, clinicId VARCHAR(64) NOT NULL, name VARCHAR(180) NOT NULL, segment VARCHAR(80) NOT NULL, templateId VARCHAR(64), mediaType VARCHAR(30) DEFAULT 'text', mediaUrl TEXT, offerCode VARCHAR(100), status VARCHAR(30) DEFAULT 'draft', scheduledAt DATETIME, sentCount INT DEFAULT 0, deliveredCount INT DEFAULT 0, readCount INT DEFAULT 0, responseCount INT DEFAULT 0, conversionCount INT DEFAULT 0, revenue DECIMAL(14,2) DEFAULT 0, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT IGNORE INTO WhatsAppSetting (clinicId, simulationMode) VALUES ('clinic-smile-expert-001', 1);
INSERT IGNORE INTO WhatsAppTemplate (id,clinicId,name,category,body,status,purpose) VALUES
('wat-001','clinic-smile-expert-001','appointment_confirmation','UTILITY','Assalam-o-Alaikum {{name}}, your appointment at {{clinic}} is confirmed for {{date}} at {{time}}. Reply if you need help.','approved','appointment'),
('wat-002','clinic-smile-expert-001','appointment_reminder_24h','UTILITY','Reminder: your appointment at {{clinic}} is tomorrow at {{time}}. Reply C to confirm or R to reschedule.','approved','appointment'),
('wat-003','clinic-smile-expert-001','post_treatment_aftercare','UTILITY','Assalam-o-Alaikum {{name}}, we hope you are comfortable after your treatment. Please follow the care instructions shared by your clinician.','approved','clinical'),
('wat-004','clinic-smile-expert-001','birthday_treatment_offer','MARKETING','Happy birthday {{name}}. Enjoy a special birthday treatment offer from {{clinic}}. Reply BOOK to reserve your visit.','approved','marketing'),
('wat-005','clinic-smile-expert-001','inactive_patient_reactivation','MARKETING','We miss you, {{name}}. Your care team at {{clinic}} would be happy to schedule your next review. Reply BOOK for available slots.','approved','marketing'),
('wat-006','clinic-smile-expert-001','payment_reminder','UTILITY','Assalam-o-Alaikum {{name}}, your pending balance is PKR {{balance}}. Contact {{clinic}} if you need billing support.','approved','billing');
INSERT IGNORE INTO WhatsAppAutomation (id,clinicId,name,triggerType,triggerValue,templateId,purpose,isActive) VALUES
('waa-001','clinic-smile-expert-001','Appointment booked confirmation','appointment_booked','immediate','wat-001','appointment',1),
('waa-002','clinic-smile-expert-001','Appointment reminder','appointment_upcoming','24h','wat-002','appointment',1),
('waa-003','clinic-smile-expert-001','Post-treatment care','treatment_completed','2h','wat-003','clinical',1),
('waa-004','clinic-smile-expert-001','Birthday treatment offer','birthday','same_day','wat-004','marketing',1),
('waa-005','clinic-smile-expert-001','Inactive patient reactivation','inactive_days','90','wat-005','marketing',1);
